services:
  hydromonitor:
    build: ../../VS_Code/Hakaton/hydromonitor_backend/hydromonitor
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro
      - ./predictions:/app/predictions
    environment:
      - HYDROMONITOR_CONFIG=/app/configs/config.yaml
    restart: unless-stopped
